name: Success Message on Push

on:
  push:
    branches:
      - main
      - contact

jobs:
  success-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Success Message
        run: echo "Push successful! Your portfolio repository has been updated."
